# Generated by Django 2.2.3 on 2019-08-14 20:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('description', models.CharField(max_length=256)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('icon', models.URLField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('is_adult', models.BooleanField()),
                ('is_leaf', models.BooleanField()),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha2', models.CharField(max_length=2)),
                ('full_name', models.CharField(max_length=512)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('agg_photos', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('balance', models.CharField(default='0', max_length=100)),
                ('barcodes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('base_photo_url', models.CharField(max_length=1024)),
                ('box_depth', models.FloatField()),
                ('box_height', models.FloatField()),
                ('box_width', models.FloatField()),
                ('depth', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('height', models.FloatField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('is_adult', models.BooleanField()),
                ('is_markdown', models.BooleanField()),
                ('is_paid_delivery', models.BooleanField()),
                ('is_price_fixed', models.BooleanField()),
                ('is_remote_store', models.BooleanField()),
                ('min_qty', models.PositiveSmallIntegerField()),
                ('minimum_order_quantity', models.FloatField()),
                ('name', models.CharField(max_length=1024)),
                ('parent_item_id', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('sid', models.PositiveSmallIntegerField()),
                ('slug', models.CharField(max_length=1024)),
                ('supply_period', models.PositiveSmallIntegerField()),
                ('weight', models.FloatField()),
                ('width', models.FloatField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('is_picture', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Option_item',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('description', models.TextField(null=True)),
                ('icon', models.CharField(max_length=1024)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModifier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('priority', models.PositiveSmallIntegerField()),
                ('value', models.CharField(max_length=100)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Item')),
                ('modifier_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Modifier')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Category')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('boolean_value', models.BooleanField()),
                ('datetime_value', models.DateTimeField()),
                ('float_value', models.FloatField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('int_value', models.PositiveIntegerField()),
                ('numrange_value', models.CharField(max_length=200)),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Attribute')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Item')),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Option_item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='nested_unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nestedUnit', to='product.Unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='trademark_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Trademark'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Unit'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='data_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.DataType'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Unit'),
        ),
    ]
