# Generated by Django 2.2.3 on 2019-08-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190815_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='balance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
