# Generated by Django 2.2.3 on 2019-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190815_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='parent_item_id',
            field=models.PositiveIntegerField(),
        ),
    ]
